### ISSUE TITLE
Face Me Tactic Card Missing

### ISSUE THREAD

**Issue by Andrivan17** [BSData/marvel-crisis-protocol#18]
FACE ME
Unaffiliated
Active
During an allied character's activation, it may spend 3 power to play this card.
Choose an enemy character within range 4 of this character.  Advance the enemy character its Speed towards this character.  After the advance, the chosen character's controller may make one attack with the chosen character.

**Comment by meestho** [comment]
I didn't see this until I finished my updates for today. I will do it tomorow. 

Thanks

**Comment by meestho** [comment]
This is done now
