### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by rylok3** [BSData/marvel-crisis-protocol#21]
Hey all, I play MCP actively and have access to enough game materials to help clean up the system. Would love to help out. Thanks!

**Comment by amis92** [comment]
@meestho you seem to be an active contributor right now. Do you approve?

**Comment by meestho** [comment]
Yes if Rylok doesnt mind reading on how to update battlescribe data. I started working as a highschool teacher in september plus started university so I'm way behind so I could use all the help I can get.

**Comment by amis92** [comment]
I'll then proceed to invite rylok so he has write acccess.

**Comment by amis92** [comment]
/invite

---
[Workflow run](https://github.com/BSData/chatops/actions/runs/340248785)
:robot: Invited @rylok3 with **push** access. Invite can be accepted on https://github.com/BSData/marvel-crisis-protocol/invitations
