### ISSUE TITLE
[Anon] Bug report: Marvel_Crisis_Protocol.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/marvel-crisis-protocol#23]
**File:** Marvel_Crisis_Protocol.gstz

**BattleScribe version:** 2.03.25

**Platform:** Android

**Dropbox:** No

**Description:** I noticed a loss of characters along with a format change. I lost whole list because characters are missing. For example, several Inhuman characters. But What characters are important to me are Crystal and Lockjaw. The loss of characters is one thing but no notice of changes or infor of characters' return.  A

**Comment by Uplink90** [comment]
Closing old issue. Complete overhaul of the repo back in October 2021. Changes to the game rules required a complete re-write.
