### ISSUE TITLE
[Anon] Bug report: Marvel Crisis Protocol.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/marvel-crisis-protocol#27]
**File:** Marvel Crisis Protocol.gstz

**BattleScribe version:** 2.03.21

**Platform:** Windows

**Dropbox:** No

**Description:** I am adding in a roster of Defenders that includes Dr Strange with a Soul Gem. I have 10 characters (Ant-man, CA (Sam Wilson), Dr Strange w/ Soul Gem, Hawkeye, Hulk, Iron Fist, Luke Cage, Spider-man, Wasp, and Wong) but I am getting an error "Roster has 1 too many selections from Character (max 10) ) I think this is left over from the old ruleset where an infinity gem took up a character roster slot but that is no longer the case.

**Comment by Uplink90** [comment]
Great catch! Sorry for the resolution delay, not sure why GH didn't notify me.

Yes, there seemed to be a few character flags leftover that were causing this bug. It is fixed in the 2.22.6.0 release posting now.

Thanks again, hope you're enjoying the pack!
